version: '3'

services:
  broker-service:
    build:
      context: ./
      dockerfile: ./broker-service.dockerfile
    restart: "no"
    ports:
      - "8090:8090"
    deploy:
      mode: replicated
      replicas: 1
